💄 use fontawesome icons in AppBar
RMI-PACTA/pacta-dashboard-svelte pull request #108
Opened 2024-12-03 14:27 UTC by jdhoffa

- 📦 gains fontawesome dependency
- use fontawesome icons instead of buttons

## Before
<img width="285" alt="Screenshot 2024-12-03 at 15 24 35" src="https://github.com/user-attachments/assets/4ced8092-2aec-4953-b0f7-64495f1fbf8a">

## After
<img width="100" alt="Screenshot 2024-12-03 at 15 27 36" src="https://github.com/user-attachments/assets/295205e8-5660-4616-92bb-c87d8da59e9f">

2024-12-03 14:38 UTC, jdhoffa commented
I will wait for @MonikaFu 's review here, as this PR adds a new dependency (and also is a totally superfluous style change, so not urgent)

2024-12-04 21:04 UTC, MonikaFu commented
Not sure if it is a good change. Maybe for GitHub it is but not sure if the save is clear enough as an icon to be honest.

2024-12-04 21:10 UTC, jdhoffa commented
> Not sure if it is a good change. Maybe for GitHub it is but not sure if the save is clear enough as an icon to be honest.

Yup totally fair enough. I thought it looked more elegant than the buttons, but perhaps also less usable. 

With that said, I imagine if a user was curious they would just click the icon, and relatively quickly understand that it saves a data_archive ¯\_(ツ)_/¯

2024-12-04 21:32 UTC, jdhoffa commented
I do feel that the icons look more professional though...

## Before
![Screenshot 2024-12-04 at 22 32 18](https://github.com/user-attachments/assets/4065351d-a2a1-46f9-9041-800760438c93)

## After
![Screenshot 2024-12-04 at 22 31 40](https://github.com/user-attachments/assets/2b36da9c-0438-45d7-b1d1-7657e2a6076a)

2024-12-05 11:30 UTC, jdhoffa commented
I added a hover effect which could be a compromise (although I'm also not convinced of this):
![Screenshot 2024-12-05 at 12 29 40](https://github.com/user-attachments/assets/cb54f847-7433-41da-a21e-b7019f90d9ce)

(Sorry the screenshot is sort of bogus)

2024-12-05 15:34 UTC, jdhoffa commented
@MonikaFu FYI, a call with @hodie lead to the following feedback: 

- The icons look more professional than the buttons
- The buttons/ text is more user-friendly than the icons
- Both features in question (GitHub, downloading an archive of the data) are likely reserved for pretty advanced users either way

A general comment was also made: 
These icons probably shouldn't be in the AppBar, but rather in a footer of the dashboard. They should exist and be available to advanced users who know what they want/ know that the buttons are there, but don't need to be front and center.

Overall actions then are:
- [ ] Review/ merge this PR
- [ ] Probably open a new issue/ PR to move icons to the footer of the page (not critically important right now)

2024-12-06 13:33 UTC, hodie commented
> @MonikaFu FYI, a call with @hodie lead to the following feedback:
> 
> * The icons look more professional than the buttons
> * The buttons/ text is more user-friendly than the icons
> * Both features in question (GitHub, downloading an archive of the data) are likely reserved for pretty advanced users either way
> 
> A general comment was also made: These icons probably shouldn't be in the AppBar, but rather in a footer of the dashboard. They should exist and be available to advanced users who know what they want/ know that the buttons are there, but don't need to be front and center.
> 
> Overall actions then are:
> 
> * [ ]  Review/ merge this PR
> * [x]  Probably open a new issue/ PR to move icons to the footer of the page (not critically important right now)
>   
>   * Tracked in [🎨 move advanced features to a less dominant part of the dashboard #135](https://github.com/RMI-PACTA/pacta-dashboard-svelte/issues/135)

Just one clarification: the conclusion was to have icons. If/when we have a proper bottom bar (like e.g. here on GitHub) there should be a text for GitHub just as there should be for Terms, Security, Contact. The download action probably does make sense to have on top since it's an action about the content. But the whole top bar will need to be reviewed once we can test it end-to-end and the dashboard is embedded into another page. Seems like a top-bar and especially the RMI logo will be confusing in that context.

2024-12-06 17:22 UTC, jdhoffa commented
FYI @MonikaFu I removed the hover over effect cause it was clunky and distracted, but this is ready for review now.

2024-12-08 10:31 UTC, MonikaFu requested changes
Adding a title to the icons results in a small banner appearing when they hover over the icon for longer. I think it adds a bit to the user friendliness without sacrificing the lean look of the icons.

2024-12-08 10:31 UTC, MonikaFu commented on src/routes/+layout.svelte
> +					>
```suggestion
title="GitHub"
					>
```

2024-12-08 10:31 UTC, MonikaFu commented on src/routes/+layout.svelte
> +					<button on:click={downloadArchive}>
```suggestion
					<button on:click={downloadArchive} title="Save data">
```

2024-12-08 10:31 UTC, MonikaFu commented on src/routes/+layout.svelte
> +					<a href="https://rmi.gitbook.io/pacta-knowledge-hub" target="_blank" rel="noreferrer">
```suggestion
					<a href="https://rmi.gitbook.io/pacta-knowledge-hub" target="_blank" rel="noreferrer" title="PACTA Knowledge Hub">
```

2024-12-09 12:43 UTC, MonikaFu approved these changes
LGTM

2024-12-09 12:51 UTC, merged